config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'user/sessions'}
  
  root to: 'tests#index'

  resources :contact_forms, only: %i[new create]
  resources :badges, only: %i[index]

    resources :tests, only: :index do
        member do
          post :start
        end
    end

    # GET /test_passages/101/result
   resources :test_passages, only: %i[show update] do
      # используем member т.к. метод result относится не к коллекции,
      # а к конкретному ресурсу
      member do
        get :result
        post :gist 
      end
   end

    namespace :admin do
      resources :badges
      resources :tests do
        # on: :member нужно для того чтоб в url был идентификатор теста, с которым работаем
        patch :update_inline, on: :member
      
        resources :questions, shallow: true, except: :index do
          resources :answers, shallow: true, except: :index 
        end
        member do
          post :start
        end
      end

        resources :gists, only: :index
    end
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :rule
  belongs_to :author, class_name: 'Admin', foreign_key: :user_id
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
    before_action :authenticate_user!
    before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
    @badge_assign = BadgeAssign.all
  end

  def show

  end

  def new
    @badge = Badge.new
  end

  def edit

  end

  def create
    @badge = Badge.new(badge_params)
    @badge.author = current_user
    if @badge.save
        redirect_to [:admin, @badge], notice: 'Badge was create successfuilly'
    else
        render :new
    end
  end

  def update
    if @badge.update(badge_params)
    redirect_to admin_badge_path
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private
    def badge_params
        params.require(:badge).permit(:title, :reward_link, :rule_id)
    end

    def find_badge
      @badge = Badge.find(params[:id])
    end

end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
    before_action :authenticate_user!
    before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
    @badge_assign = BadgeAssign.all
  end

end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
    <td><%= User.where(id: badge.user_id)[0].login %></td>
    <td><%= badge.title %></td>
    <td><%= badge.reward_link %></td>
    <td><%= Rule.where(id: badge.rule_id)[0].title %></td>
    <td><%= link_to 'Исправить', 
                        edit_admin_badge_path(badge) %>
    </td>
    <td>
    <%= link_to 'Удалить',
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: "Вы уверены?"} %>
    </td>
</tr>

app/views/admin/badges/_form.html.erb
<%# binding.pry%>
<%= form_with model: [:admin, @badge], local: true do |form| %>

    <%= render 'shared/errors', resource: @badge %>
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title, id: :badge_title %>
    </p>

    <p>
      <%= form.label :reward_link %><br>
      <%= form.text_field :reward_link, id: :badge_reward_link %>
    </p>
    <p>
      <%= form.label :rule_id %><br>
      <%= form.collection_select :rule_id, Rule.all, :id, :title, prompt: true %>


    <p><%= form.submit %></p>

<% end %>

app/views/admin/badges/edit.html.erb
<h1> Исправить </h1>

<%= render 'form' %>

<%= link_to 'Show', admin_badge_path(@badge.id) %>

app/views/admin/badges/index.html.erb
<h3> Таблица всех существующих бэйджей </h3>

<p>
  <%= link_to "Создать новый бэйдж", new_admin_badge_path %>
</p>

<table class="table">
  <tr>
    <th> Автор </th>
    <th> Название </th>
    <th> Награда </th>
    <th> За что </th>
    <th colspan="2"> Управление </th>
  </tr>

    <%= render @badges %>
    
</table>



<%= link_to "Список тестов", admin_tests_path %>

app/views/admin/badges/new.html.erb
<h1> Создание нового бэйджа </h1>

<%= render 'form' %>

<%= link_to "Список тестов", admin_tests_path %>

app/views/admin/badges/show.html.erb
<h3> Информация по бэйджу </h3>


<p> <strong> Автор: </strong>
  <%= User.where(id: @badge.user_id)[0].login%>
</p>
<p> <strong> Название: </strong>
  <%= @badge.title%>
</p>
<p> <strong> Награда: </strong>
  <%= @badge.reward_link%>
</p>
<p> <strong> За что: </strong>
  <%= Rule.where(id: @badge.rule_id)[0].title%>
</p>

<%= link_to 'Список бэйджей', admin_badges_path %>