config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'user/sessions'}
  
  root to: 'tests#index'

  resources :contact_forms, only: %i[new create]
  resources :badges, only: %i[index]

    resources :tests, only: :index do
        member do
          post :start
        end
    end

    # GET /test_passages/101/result
   resources :test_passages, only: %i[show update] do
      # используем member т.к. метод result относится не к коллекции,
      # а к конкретному ресурсу
      member do
        get :result
        post :gist 
      end
   end

    namespace :admin do
      resources :badges
      resources :tests do
        # on: :member нужно для того чтоб в url был идентификатор теста, с которым работаем
        patch :update_inline, on: :member
      
        resources :questions, shallow: true, except: :index do
          resources :answers, shallow: true, except: :index 
        end
        member do
          post :start
        end
      end

        resources :gists, only: :index
    end
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :test 
    has_many :answers
    has_many :gists

    validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: [:create]

  SUCCESS_LEVEL = 85

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.current_question = next_question
    save!
  end

  def success_level
    SUCCESS_LEVEL
  end

  def completed?
    current_question.nil?
  end

  def sum_questions
    test.questions.count
  end

  def number_of_question
    test.questions.index(current_question) + 1
  end

  def persent_of_success
    (self.correct_questions.to_f / self.test.questions.count * 100).round(2)
  end

  def check_test
    if self.persent_of_success >= SUCCESS_LEVEL
      return 'Тест пройден успешно'
    else 
      return  'Тест не пройден'
    end
  end

  def color_for_message
    if self.persent_of_success >= SUCCESS_LEVEL
      return 'green'
    else 
      return  'red'
    end
  end


  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

 
  def correct_answer?(answer_ids)
    answer_ids ||= []
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    #можем вызвать .correct поскольку у нас есть такой scope в модели answer
    current_question.answers.correct
  end

    #экземпляр test здесь можно использовать поскольку у нас есть belongs_to :test
    #т.е. связность моделей позволяет использовать связные экземпляры этих моделей
  def next_question
    # запись 'id > ?', current_question.id означает что выбираются только те вопросы, у которых id больше чем у текущего
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :authenticate_user!  
  before_action :set_test_passage, only: %i[show update result gist first_time_pass_test]

    def show

    end

    def result
      @count_of_questions = @test_passage.test.questions.count
      @correct_answers = @test_passage.correct_questions
      @persent_of_success = @test_passage.persent_of_success
      @check_test = @test_passage.check_test
      @color_for_message = @test_passage.color_for_message
    end

    def first_time_pass_test
      #binding.pry
      @badge_id = Badge.where(rule_id: Rule.where(title: 'Пройден тест с первого раза').ids).ids[0]
      BadgeAssign.create(user_id: current_user.id, badge_id: @badge_id) if @test_passage.persent_of_success >= @test_passage.success_level &&
                                                                        TestPassage.where(user_id: current_user).where(test_id: @test_passage.test.id).count == 1
      #binding.pry
    end

    def update
        @test_passage.accept!(params[:answer_ids])
        
        if @test_passage.completed?
          first_time_pass_test
          
          TestsMailer.completed_test(@test_passage).deliver_now
          redirect_to result_test_passage_path(@test_passage)

        else
          render :show
        end
    end

    def gist
      gist_service = GistQuestionService.new(@test_passage.current_question)
      result = gist_service.call
      
      flash_options = if gist_service.success?
        gist_url = result.html_url
        gist_url_tag = %Q[<a href="#{gist_url}" target="_blank">gist.github.com</a>]
        current_user.gists.create(question: @test_passage.current_question,
                                  gist_url: gist_url)
        { notice: t('.success', url: gist_url_tag) }
      else
        { alert: t('.failure') }
      end

      redirect_to @test_passage, flash_options
    end

    private

    def set_test_passage
      @test_passage = TestPassage.find(params[:id])
    end

end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
end

app/views/test_passages/result.html.erb
<h3> <%= t('.header', title: @test_passage.test.title) %> </h3>

<div id="myProgressResult">
  <div id="myBarResult"></div>
</div>

<%= content_tag :div, "Всего вопросов: #{@count_of_questions}",
                class: 'questions',
                data: {sum_questions: @count_of_questions} %>

<%= content_tag :div, "Количество правильных ответов: #{@correct_answers}", 
                class: 'answers',
                data: {correct_answers: @correct_answers} %>

  <div style='display: inline-flex'>
    <div>
        Процент успеха:&nbsp
    </div>  
    <div class= <%= @color_for_message %> >
      <%= @persent_of_success  %> %
    </div>
    </div>
    <br>
    <div class= <%= @color_for_message %>>
      <%= @check_test  %>
    </div>
  
<br>

<%= link_to 'List of tests', current_user.admin? ? admin_tests_path : tests_path %>

app/views/test_passages/show.html.erb
<h4> <%= t('.header_test', title: @test_passage.test.title) %> </h4>

<div id="myProgress">
  <div id="myBar"></div>
</div>

<%= content_tag :span, "Это #{@test_passage.number_of_question} вопрос из #{@test_passage.test.questions.count}",
  class: 'question', 
  data: {sum: @test_passage.test.questions.count, num: @test_passage.number_of_question} %>

<p>
    <b><%= @test_passage.current_question.body %></b>
</p>


<%= form_with url: test_passage_path(@test_passage), local: true, method: :put do |form| %>
    <%= form.collection_check_boxes :answer_ids, @test_passage.current_question.answers, :id, :body, include_hidden: false  do |b| %>
      <p>
        <%= b.check_box id: "answer_ids_#{b.object.id}"%>
        <%= b.label%>
      </p>
    <% end %>

    <p> <%= link_to 'Gist Question', gist_test_passage_path(@test_passage), method: :post%> </p>
    <p> <%= form.submit 'Next', class: "btn btn-primary"%> </p>
<% end %>