config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'user/sessions'}
  
  root to: 'tests#index'

  resources :contact_forms, only: %i[new create]
  resources :badges, only: %i[index]

    resources :tests, only: :index do
        member do
          post :start
        end
    end

    # GET /test_passages/101/result
   resources :test_passages, only: %i[show update] do
      # используем member т.к. метод result относится не к коллекции,
      # а к конкретному ресурсу
      member do
        get :result
        post :gist 
      end
   end

    namespace :admin do
      resources :badges
      resources :tests do
        # on: :member нужно для того чтоб в url был идентификатор теста, с которым работаем
        patch :update_inline, on: :member
      
        resources :questions, shallow: true, except: :index do
          resources :answers, shallow: true, except: :index 
        end
        member do
          post :start
        end
      end

        resources :gists, only: :index
    end
end

app/models/admin.rb
class Admin < User

    validates :first_name, presence: true
    validates :last_name, presence: true
    
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question

    scope :correct, ->  { where(correct: true)}

    validates :body, presence: true
    validate :validate_quantity, on: :create

    def validate_quantity
      #errors.add(:quantity, "Maximum is 4 answers") if question.answers.size >= 4
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :rule
  belongs_to :author, class_name: 'Admin', foreign_key: :user_id
end

app/models/badge_assign.rb
class BadgeAssign < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tests
    default_scope -> {order(title: :asc) }
    validates :title, presence: true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
    attribute :name,      :validate => true
    attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
    attribute :file,      :attachment => true
  
    attribute :message
    attribute :nickname,  :captcha  => true
  
    # Declare the e-mail headers. It accepts anything the mail method
    # in ActionMailer accepts.
    def headers
      {
        :subject => "My Contact Form",
        :to => "your.email@your.domain.com",
        :from => %("#{name}" <#{email}>)
      }
    end
  end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :test 
    has_many :answers
    has_many :gists

    validates :body, presence: true
end

app/models/rule.rb
class Rule < ApplicationRecord
  has_many :badges
end

app/models/test.rb
class Test < ApplicationRecord

  has_many :test_passages
  has_many :users, through: :test_passages
  
  belongs_to :category
  has_many :questions
  belongs_to :author, class_name: 'User', foreign_key: :user_id

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  scope :simple_level, ->  { where(level: 0..1)}
  scope :average_level, -> { where(level: 2..4)}
  scope :high_level, ->    { where(level: 4..Float::INFINITY)}
  scope :show_tests, -> (category) { where(category_id: Category.where(title: category).ids)}

end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: [:create]

  SUCCESS_LEVEL = 85

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    self.current_question = next_question
    save!
  end

  def success_level
    SUCCESS_LEVEL
  end

  def completed?
    current_question.nil?
  end

  def sum_questions
    test.questions.count
  end

  def number_of_question
    test.questions.index(current_question) + 1
  end

  def persent_of_success
    (self.correct_questions.to_f / self.test.questions.count * 100).round(2)
  end

  def check_test
    if self.persent_of_success >= SUCCESS_LEVEL
      return 'Тест пройден успешно'
    else 
      return  'Тест не пройден'
    end
  end

  def color_for_message
    if self.persent_of_success >= SUCCESS_LEVEL
      return 'green'
    else 
      return  'red'
    end
  end


  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

 
  def correct_answer?(answer_ids)
    answer_ids ||= []
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    #можем вызвать .correct поскольку у нас есть такой scope в модели answer
    current_question.answers.correct
  end

    #экземпляр test здесь можно использовать поскольку у нас есть belongs_to :test
    #т.е. связность моделей позволяет использовать связные экземпляры этих моделей
  def next_question
    # запись 'id > ?', current_question.id означает что выбираются только те вопросы, у которых id больше чем у текущего
    test.questions.order(:id).where('id > ?', current_question.id).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

    attr_reader :password
    attr_writer :password_confirmation

    has_many :badges
    has_many :gists
    has_many :test_passages
    has_many :tests, through: :test_passages
    has_many :author_tests, class_name: 'Test'

    validates :email, presence: :true,
                      uniqueness: true, 
                      :format => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    def test_list (level)
        Test.joins('JOIN tests_users ON tests.id = tests_users.test_id')
            .where("tests.level = ?",level).where("tests_users.user_id = ?", id)
    end

    def test_passage(test)
        test_passages.order(id: :desc).find_by(test_id: test.id)
    end

    def admin?
        self.is_a?(Admin)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  HASH_FOR_BOOTSTRAP={alert: 'alert alert-danger', notice: 'alert alert-primary'}
  def current_year
    Date.current.year
  end
    
  def github_url(author, repo)
    link_to  'Test-Guru', "https://github.com/#{author}/#{repo}", target: '_blank'
  end

  def flash_class(key)
    HASH_FOR_BOOTSTRAP[key.to_sym]
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
    def admin_redirection
        redirect_to admin_tests_path
    end
  end
  

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper

    TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

    def test_level(test)
      TEST_LEVELS[test.level] || :hero
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'shared/nav'%>
    <div class="container">
        <%=render 'shared/flash'%>
        <%= yield %>
    </div>
      <%= render 'shared/footer'%>
  </body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'shared/nav'%>
    <div class="container">
        <%=render 'shared/flash'%>
        <%= yield %>
    </div>
      <%= render 'shared/footer'%>
  </body>

</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
    <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.id } do %>
        <h2> 
             <%= t('.header', count: resource.errors.count)%> :
        </h2>

        <ul>
            <% resource.errors.full_messages.each do |message| %>
            <li> <div class="alert alert-danger" role="alert">
                    <%= message%>
                 </div>
            </li>
            <%end%>
        <ul>
    <%end%>
<%end%>

app/views/shared/_flash.erb
    <% flash.each do |key, value| %>
      <%= content_tag :div, value.html_safe, class: "#{flash_class(key)} text-center" %>
    <% end %>

app/views/shared/_footer.html.erb
 
  <footer class="text-right"> <hr>
    Project: <%= github_url('yuriskorobogatov', 'Test-Guru') %> created by Unrealimp &reg; <%= current_year %> <br>
    это учебный проект в онлайн-школе  <a href="https://thinknetica.com/" target="blank">Thinknetica</a> <br>
    представляющий собой интерактивный тест для техников и монтажников кабельного телевидения
  </footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand'%>

    <span class="navbar-text">
    <% if user_signed_in? %>
      <p class="nav"> <%= t('.welcome') %><b> &nbsp <%= current_user.email%> </b> &nbsp <%= t('.guru') %> |&nbsp
          <%= link_to "#{t('.log_out')}", destroy_user_session_path, method: :delete%></p>
      <p class="nav"> <%= link_to "#{t('.admin_panel')}", admin_tests_path if current_user.admin?%> </p>
      <p class="nav"> <%= link_to "#{t('.contact_us')}", new_contact_form_path, class: :btn if current_user.admin? == false%>
    <% else%>  
      <p class="nav user"> <%= link_to "#{t('.log_in')}", new_user_session_path%>  </p>
      <p class="nav user"> <%= link_to "#{t('.registration')}", new_user_registration_path%> </p>
    <% end %>

    </span>
</nav>