config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {sessions: 'user/sessions'}
  
  root to: 'tests#index'

  resources :contact_forms, only: %i[new create]
  resources :badges, only: %i[index]

    resources :tests, only: :index do
        member do
          post :start
        end
    end

    # GET /test_passages/101/result
   resources :test_passages, only: %i[show update] do
      # используем member т.к. метод result относится не к коллекции,
      # а к конкретному ресурсу
      member do
        get :result
        post :gist 
      end
   end

    namespace :admin do
      resources :badges
      resources :tests do
        # on: :member нужно для того чтоб в url был идентификатор теста, с которым работаем
        patch :update_inline, on: :member
      
        resources :questions, shallow: true, except: :index do
          resources :answers, shallow: true, except: :index 
        end
        member do
          post :start
        end
      end

        resources :gists, only: :index
    end
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :test 
    has_many :answers
    has_many :gists

    validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

    before_action :authenticate_user!
    before_action :set_test, only: [:index, :create, :new]
    before_action :set_question, only: [:show, :destroy, :edit]
  
    rescue_from ActiveRecord::RecordNotFound, with: :question_not_found
  
      #Список вопросов теста и сам тест
    def index
      @test_name = @test.title
      @result = @test.questions
    end
  
    def show
     
    end
  
    def new
      @question = @test.questions.new
    end
  
    def create
      @question = @test.questions.new(question_params)
  
      if @question.save
         redirect_to admin_question_path(@question.id)
      else
        ["Error!", @question.errors.full_messages, "Question can not be created!"]
        render :new
      end
    end
    #чтобы получить ресурс
    def edit
     
    end
    #чтобы обновить ресурс
    def update 
      @question = Question.find(params[:id])
  
      if @question.update(question_params)
         redirect_to admin_question_path
      else
        ["Error!", @question.errors.full_messages, "Question can not be updated!"]
        render :edit
      end
    end
  
    def destroy
      @question.destroy
      redirect_to admin_test_path(@question.test.id)
    end
  
    private
  
    def set_test
      @test = Test.find(params[:test_id])
    end
  
    def set_question
      @question = Question.find(params[:id])
    end
  
    def question_params
      #параметр :test_id тут не добавляю т.к. получаю его через ассоциации
      params.require(:question).permit(:body)
    end
  
    def question_not_found
      render plain: 'Question was not found'
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    if question.new_record?
      "Create New #{question.test.title} Question"
    else
      "Edit #{question.test.title} Question"
    end
  end
end

app/views/admin/questions/_form.html.erb
<%= form_with(model: [:admin, @test, @question], local: true) do |form| %>

<%= render 'shared/errors', resource: @question%>

        <p>
            <%= form.label :body %> <br>
            <%= form.text_area :body, id: :question_body , rows: 7, cols: 60%>
        </p>

        <p>
            <%= form.label :test_id%> <br>
            <%= form.collection_select(:test_id, Category.all, :id, :title, promt: true) %>
        </p>

        <%= form.submit%>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.id %></td>
  <td><%= question.body%></td>
  <td><%= question.test_id %></td>
  <td>  <%= link_to 'Show', admin_question_path(question) %> </td>
  <td>  <%= link_to 'Edit', edit_admin_question_path(question) %> </td>
  <td>
    <%= link_to 'Delete',
                admin_question_path(question),
                method: :delete,
                data: { confirm: 'Are you sure?'} %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<h1><%= question_header(@question) %> </h1>

<%= render 'form'%>

app/views/admin/questions/index.html.erb
<h3> <%= @test_name.capitalize%> </h3>
<br>

<table>
    <tr>
        <th>Вопрос</th>
        <th colspan="3">Действие</th>
        
    <tr>

    <% @result.each do |question| %>
        <tr>
            <td><%=  question.body %></td>
            <td><%= link_to 'Show', admin_question_path(question)%></td>
            <td><%= link_to 'Edit', edit_admin_question_path(question)%></td>
            <td>
                <%= link_to 'Delete',
                            admin_question_path(question),
                            method: :delete,
                            data: {confirm: 'Подтвердите удаление'}
                             %>
            </td>
           
            
        <tr>
    <%end%>
</table>

<%= link_to 'Новый вопрос', new_test_question_path %>

app/views/admin/questions/new.html.erb
<h1><%= question_header(@question) %> </h1>

<%= render 'form'%>
<br>
<%= link_to 'Back', admin_test_path(@test)%>
   

app/views/admin/questions/show.html.erb
<strong> Body: </strong> <br><br>
Вопрос: <%= @question.body%>
<br><br>

<h2> Answers </h2>
<%= link_to 'New answer', new_admin_question_answer_path(@question)%>

<ol>
    <%= render @question.answers %>
</ol>


<%= link_to 'Edit question', edit_admin_question_path(@question)%>

<%= link_to 'New question', "/admin/tests/#{@question.test.id}/questions/new" %> 

<%= link_to 'List of questions', "/admin/tests/#{@question.test.id}" %>